"""Premium AI Interview Coach Upgrade

Revision ID: 9f640e54f3fc
Revises: fe478d88ee66
Create Date: 2026-07-14 10:30:14.707582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f640e54f3fc'
down_revision: Union[str, Sequence[str], None] = 'fe478d88ee66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    import json
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professionalism_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('grammar_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pacing_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('overall_feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('missing_points', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('priority_improvements', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('tips', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('answer_pacing_feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recommended_framework', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ideal_answer_structure', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('ideal_answer_example', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('estimated_time_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('actual_word_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('actual_estimated_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('filler_word_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ideal_word_count', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('interviewer_impression', sa.JSON(), nullable=False))
        batch_op.alter_column('strengths',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False)
        batch_op.alter_column('weaknesses',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False)

    # Data migration: Convert old strings to JSON arrays
    conn = op.get_bind()
    res = conn.execute(sa.text("SELECT id, strengths, weaknesses FROM candidate_answers"))
    
    for row in res:
        ans_id = row[0]
        s_val = row[1]
        w_val = row[2]
        
        # Safely convert strengths
        if not s_val or (isinstance(s_val, str) and s_val.strip() == ""):
            new_s = '[]'
        elif isinstance(s_val, str) and s_val.startswith('['):
            new_s = s_val # Already JSON
        else:
            new_s = json.dumps([str(s_val)])
            
        # Safely convert weaknesses
        if not w_val or (isinstance(w_val, str) and w_val.strip() == ""):
            new_w = '[]'
        elif isinstance(w_val, str) and w_val.startswith('['):
            new_w = w_val
        else:
            new_w = json.dumps([str(w_val)])
            
        conn.execute(
            sa.text("UPDATE candidate_answers SET strengths = :s, weaknesses = :w WHERE id = :id"),
            {"s": new_s, "w": new_w, "id": ans_id}
        )


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_answers', schema=None) as batch_op:
        batch_op.alter_column('weaknesses',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('strengths',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('interviewer_impression')
        batch_op.drop_column('ideal_word_count')
        batch_op.drop_column('filler_word_count')
        batch_op.drop_column('actual_estimated_time')
        batch_op.drop_column('actual_word_count')
        batch_op.drop_column('estimated_time_seconds')
        batch_op.drop_column('ideal_answer_example')
        batch_op.drop_column('ideal_answer_structure')
        batch_op.drop_column('recommended_framework')
        batch_op.drop_column('answer_pacing_feedback')
        batch_op.drop_column('tips')
        batch_op.drop_column('priority_improvements')
        batch_op.drop_column('missing_points')
        batch_op.drop_column('overall_feedback')
        batch_op.drop_column('pacing_score')
        batch_op.drop_column('grammar_score')
        batch_op.drop_column('professionalism_score')

    # ### end Alembic commands ###
