"""Initial migration

Revision ID: fe478d88ee66
Revises: 
Create Date: 2026-07-14 09:41:18.031792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe478d88ee66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_coding_submissions_id'), table_name='coding_submissions')
    op.drop_table('coding_submissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_submissions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('question_id', sa.VARCHAR(), nullable=False),
    sa.Column('code', sa.TEXT(), nullable=False),
    sa.Column('execution_output', sa.TEXT(), nullable=True),
    sa.Column('execution_time', sa.FLOAT(), nullable=True),
    sa.Column('memory_used', sa.FLOAT(), nullable=True),
    sa.Column('compilation_error', sa.TEXT(), nullable=True),
    sa.Column('test_cases_passed', sa.INTEGER(), nullable=True),
    sa.Column('test_cases_total', sa.INTEGER(), nullable=True),
    sa.Column('code_review_feedback', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_submissions_id'), 'coding_submissions', ['id'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('question_id', sa.VARCHAR(), nullable=False),
    sa.Column('answer_text', sa.TEXT(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('correctness', sa.FLOAT(), nullable=True),
    sa.Column('communication', sa.FLOAT(), nullable=True),
    sa.Column('technical_depth', sa.FLOAT(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('problem_solving', sa.FLOAT(), nullable=True),
    sa.Column('best_practices', sa.FLOAT(), nullable=True),
    sa.Column('strengths', sa.TEXT(), nullable=True),
    sa.Column('weaknesses', sa.TEXT(), nullable=True),
    sa.Column('suggestions', sa.TEXT(), nullable=True),
    sa.Column('follow_up_question', sa.TEXT(), nullable=True),
    sa.Column('follow_up_answer', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_id'), 'answers', ['id'], unique=False)
    # ### end Alembic commands ###
